# __Author__      = " Jacob Paul "

version: '3'
services:
  backend:
    container_name: "sih_backend"
    image: "siqsessedge/sih-api-python:v6.0"
    environment:
      "MQTT_BROKER_IP": "167.233.7.5"
      "MQTT_BROKER_PORT": "1883"
      "MQTT_MESSAGE_TOPIC": "IoT_SM/Message"
      "MQTT_GPS_MESSAGE_TOPIC": "IoT_SM/GPS"
      "APPLICATION_MODE": "web"
      "MONGO_CONNECTION_STRING": "167.233.7.5:27017"
      "REDIS_IP": "172.11.0.3"
      "REDIS_PORT": "6379"
      "SERIALPORT": "COM3"
    ports:
      - "8090:8000"
    volumes:
      - "./Files/JsonConfig/:/iot_sm/App/JsonConfig/"
      - "/etc/timezone:/etc/timezone"
      - "/etc/localtime:/etc/localtime"
    depends_on:
      - redis
    # devices:
    #   - /dev/ttyUSB0:/dev/ttyUSB0
    #   - /dev/ttyUSB1:/dev/ttyUSB1
    networks:
      sih-sm-network:
        ipv4_address: 172.11.0.2
    restart: always
  
  redis:
    image: "redis:5"
    container_name: "sih_redis"
    networks:
      sih-sm-network:
        ipv4_address: 172.11.0.3
    restart: always

networks:
  sih-sm-network:
    ipam:
      config:
        - subnet: 172.11.0.0/16
