# __Author__      = " Jacob Paul "

version: '3'
services:

  mongo:
    image: "mongo:bionic"
    container_name: "mongoDB"
    ports:
      - "27016:27017"
    volumes:
      - './DockerFiles/MongoDB/data:/data/db'
    networks:
      cloud-network:
        ipv4_address: 173.12.0.4
    restart: always


  mongo-express:
    image: mongo-express
    environment:
      - ME_CONFIG_MONGODB_SERVER=173.12.0.4
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
      - ME_CONFIG_MONGODB_AUTH_USERNAME=devroot
      - ME_CONFIG_MONGODB_AUTH_PASSWORD=devroot
      - ME_CONFIG_BASICAUTH_USERNAME=devroot
      - ME_CONFIG_BASICAUTH_PASSWORD=devroot
    depends_on:
      - mongo
    ports:
      - "8888:8081"
    networks:
      cloud-network:
        ipv4_address: 173.12.0.5
    restart: always


networks:
  cloud-network:
    ipam:
      config:
        - subnet: 173.12.0.0/16


