# __Author__      = " Jacob Paul "

version: '3'
services:
  backend:
    image: "siqsessedge/sih-api-python:v1.2"
    environment:
      "MQTT_BROKER_IP": "localhost"
      "MQTT_BROKER_PORT": "1883"
      "MQTT_MESSAGE_TOPIC": "IoT_SM/Message"
      "APPLICATION_MODE": "web"
      "MONGO_CONNECTION_STRING": "localhost:27016"
      "REDIS_IP": "localhost"
      "REDIS_PORT": "6379"
    ports:
      - "8000:8000"
    restart: always
  
  redis:
    image: "redis:5"
    ports:
      - "6379:6379"
